services:
  worker:
    build: ./worker
    volumes:
      - ./worker:/usr/local/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    depends_on:
      queue:
          condition: service_healthy

  queue:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  go-mod-cache:
  go-build-cache:
