apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      serviceAccountName: dispatcher
      containers:
        - name: dispatcher
          image: dispatcher:latest
          imagePullPolicy: Never
          volumeMounts:
          - mountPath: /app/target
            name: rust-target
            readOnly: false
      volumes:
      - name: rust-target
        hostPath:
          path: /dispatcher/target
          type: DirectoryOrCreate
